@echo off

set content_type="Content-Type: application/json"
set token=%1
set token=%token:'=%
# set token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGF2ZSI6ImMxMzQxMzkyIiwib2F1dGhBY2Nlc3NUb2tlbiI6Ik9IOUdVTHF2VFVSNXZSd1dUb21USDJobTJxSSIsIm5vbWUiOiJFUklDSyBORVZFUyBCQVRJU1RBIERFIEFSQVVKTyIsIm5vbWVHdWVycmEiOiJFUklDSyIsImVtYWlsIjoiYzEzNDEzOTJAaW50ZXJuby5iYi5jb20uYnIiLCJwYXBlaXMiOlt7InJvbGUiOiJBTE1GRCIsImJ1c2luZXNzQXJlYSI6IlQ5OSJ9LHsicm9sZSI6IkFMTUZEIiwiYnVzaW5lc3NBcmVhIjoiQ0JPIn0seyJyb2xlIjoiQUxNRkQiLCJidXNpbmVzc0FyZWEiOiJDQkcifSx7InJvbGUiOiJBTE1GRCIsImJ1c2luZXNzQXJlYSI6IkdDQiJ9LHsicm9sZSI6IkFMTUZEIiwiYnVzaW5lc3NBcmVhIjoiR1JQIn0seyJyb2xlIjoiQUxNRkQiLCJidXNpbmVzc0FyZWEiOiJBVEgifSx7InJvbGUiOiJBTE1GRCIsImJ1c2luZXNzQXJlYSI6IkNCTiJ9XSwicHJlZml4b0RlcGVuZGVuY2lhIjoiOTkxMCIsInVvckRlcGVuZGVuY2lhIjoiMjAzMTkiLCJjb2RpZ29SZXNwb25zYWJpbGlkYWRlRnVuY2lvbmFsIjoiMCIsInVzdWFyaW9GYWtlIjpmYWxzZSwiaWF0IjoxNzM1MzI2Mzk0LCJleHAiOjE3MzUzNDc5OTR9.8hYVY0EdTdLkBTEonMkJqUoibvQwucXCeCDQWppFseI
set authorization="Authorization: Bearer %token%"
set suite_id=%2
set suite_id=%suite_id:'=%
set scenario_id=%3
set scenario_id=%scenario_id:'=%
curl -X POST https://testesuaapi.ftabb.intranet.bb.com.br/api/cenarios/%scenario_id%/clonar/%suite_id% -H %content_type% -H %authorization%